require_relative './config/environment'
require 'sinatra/activerecord/rake'  #Has an agglomeration of all the common active record rake tasks. To see all these available tasks we run rake -T

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end
